### ISSUE TITLE
postgresqldb and mysqldb modules do not provision databases

### ISSUE THREAD

**Issue by krancour** [Azure/meta-azure-service-broker#114]
Contrasted with the existing sqldb module, which creates SQL Servers _and_ databases on those servers, the new postgresqld and mysqldb modules provision servers _only_; and not databases...

I believe this is something of a problem because, generally speaking, a _database_ is what a user or application seeks to provision and bind to. The requirement that the database live on a server is just an incidental detail.

Related: the bind operation for both of these new modules is returning the server admin's credentials. This probably isn't ideal either. It would be preferable to create a new set of credentials for each application that binds, and in this way, those credentials can be revoked upon unbind.

**Comment by zhongyi-zhang** [comment]
@krancour, I agree with you.
But for MySQL and PostgreSQL, when user deletes the service instance, the broker shouldn't delete the database only and leave the server just like what sqldb does because they are billed based on the server (on the database for sqldb).
If deleting server, that means 1 server : 1 instance. I think it is better to allow app to manage the whole MySQL instance instead of a database. Maybe the broker should still create a database. And app can create more databases itself if it wants?

For the part a user for a binding, I totally agree with you. But there is not REST API to create a user either. It need to follow the complicated method in sqldb. I am considering to implement that.

**Comment by kevinhillinger** [comment]
@thomas1206 is this still relevant or can we close?

**Comment by zhongyi-zhang** [comment]
OSBA did the job.
