### ISSUE TITLE
Proposal: wherever possible, provide sensible defaults for parameters

### ISSUE THREAD

**Issue by krancour** [Azure/meta-azure-service-broker#115]
There's probably some room for debate in terms of which parameters are affected, but I believe that there are probably several cases where overall user experience can be improved by providing sensibly defaulted parameters (instead of absolutely requiring a user to provide them).

For example...

In provisioning a database server (SQL Server, Postgres server, MySQL server-- applies to all), it's probably not 100% necessary to require the user to provide an admin username and password. In the absence of this information, a username and strong password can easily be generated. By omitting those values, a user carrying out the provisioning _who doesn't require administrative access to the server_ is not burdened with having to provide extraneous details _and_ they're not burdened with a level of access that they neither want nor need. For the use cases where the user carrying out provisioning _does_ care about these details, they are still able to provide them explicitly. (i.e. This proposal isn't a breaking change.)

Some other parameters that this concept _might_ apply to:

- Firewall rules. Is there a sensible, default firewall rule that can be provided for most services (something permissive)?
- Database names? In many cases, the _name_ of a database that's being provisioned might not be important to the user provisioning it. In many cases, they might only care that a database exists and that they can access it. They will learn its name by binding to it.

Again... I propose that we _not prohibit_ such parameters from being provided explicitly, but only that we apply sensible defaults so as not to _require_ them for the many use cases in which such information is extraneous.

**Comment by arschles** [comment]
+1 on this. My point of view is from the [service-catalog](https://github.com/kubernetes-incubator/service-catalog) project. This functions basically as the equivalent of a marketplace in Cloud Foundry terms.

Service-Catalog is a layer between a Kubernetes cluster and the brokers. When broker servers require parameters, service-catalog must require the users to pass parameters from Kubernetes. We'd like to avoid this scenario whenever possible, so that users don't need to know as many details about the backing brokers, and instead can focus on what services they are being provided.

For example, instead of requiring that a user is provisioning an Azure PostgreSQL instance (because they have to know the parameters for the Azure broker), we'd rather they just know that they are provisioning a PostgreSQL instance, without knowing which cloud it's on. Having this functionality allows a user to make their application more portable across clouds, and that's an important goal for service-catalog.

**Comment by krancour** [comment]
And to follow up on @arschles comment above, Open Service Broker is looking to introduce schemas in a future version of the spec that will further promote uniform parameter names and credential properties across providers... but until that is in place (and until brokers implement it), requiring fewer parameters is a tactical step toward promoting better (albeit imperfect) portability.
