### ISSUE TITLE
Hit an error when following up the instructions for service broker test

### ISSUE THREAD

**Issue by lilyfang** [Azure/meta-azure-service-broker#79]
By following up the instructions @https://github.com/Azure/meta-azure-service-broker/tree/master/test, an error will be hit as below, 
li@liubuntu:~/meta-azure-service-broker$ npm test
> meta-azure-service-broker@1.2.0 test /home/li/meta-azure-service-broker
> npm -s run-script jshint && npm -s run-script cover
/usr/bin/env: ‘node’: No such file or directory
npm ERR! Test failed.  See above for more details

**Comment by bingosummer** [comment]
`/usr/bin/env: ‘node’: No such file or directory` means that the node engine (nodejs) is not installed correctly. You need to install nodejs and npm correctly.

For `Ubuntu 14.04`, you need to run `sudo apt-get install nodejs-legacy`. I guess that you are using `sudo apt-get install nodejs` on `Ubuntu 14.04` which creates a link `/usr/bin/nodejs` instead of `/usr/bin/node`. If that's the case, could you please try the command `ln -s /usr/bin/nodejs /usr/bin/node` to create the soft link manually?

**Comment by lilyfang** [comment]
Creating a soft link manually solves the issue. However, I am using Ubuntu 16.04, not 14.04.
